version: '3.9'
services:

  web:
    build: .
    command: gunicorn python.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    depends_on:
      - db

  db:
    image: postgres:11-alpine 
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    depends_on:
      - web
        
volumes:
  postgres_data:
  staticfiles:
  media: